blank_issues_enabled: false
contact_links:
  - name: Check past feature suggestions
    url: https://github.com/altcipher/repr/discussions/categories/ideas-and-feature-suggestions
    about: Visit the Feature Suggestions forum to view and discuss existing feature suggestions.
  - name: Check past help topics
    url: https://github.com/altcipher/repr/discussions/categories/q-a
    about: Visit the Question & Answers forum to view and discuss help topics.
  - name: Create help request
    url: https://github.com/altcipher/repr/discussions/new?category=q-a
    about: Create a support ticket to get help from developers.
  - name: Suggest a feature
    url: https://github.com/altcipher/repr/discussions/new?category=ideas-and-feature-suggestions
    about: Suggest new features for repr!
