name: Bug Report
description: Report a bug in repr.
title: '[Bug]: '
labels: 'bug: unconfirmed'
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to report a repr bug! Fill out the form below to provide us with info to help fix the bug.
      Only use this if you're 100% sure you've found a bug and can reproduce it. If you're looking for general help with repr, try the Wiki or Q&A forum.
- type: dropdown
  attributes:
    label: Type of bug
    description: What type of bug is this? Choose all that apply.
    multiple: true
    options:
      - Performance issue or memory leak
      - Data loss
      - Exploit
      - Compatibility issue
      - Error in console
      - Other unexpected behaviour
  validations:
    required: true
- type: textarea
  attributes:
    label: "Version Output"
    description: Run `./repr version` in the console, then copy and paste the full output of the command into this box.
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug description
    description: Describe roughly what the bug is here.
    placeholder: |
      Example: "When running /nuke after putting everyone into adventure mode, there aren't any explosions..."
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Provide an example of how to trigger the bug.
    placeholder: |
      Example:
      1. Have at least 3 people online
      2. Run `/gma *` to put everyone into adventure mode
      3. Run `/nuke`
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behaviour
    description: Explain what you should expect to happen.
    placeholder: |
      Example: "Everything should explode!"
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behaviour
    description: Explain what actually happens.
    placeholder: |
      Example: "Everything doesn't explode :("
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      In the text box below, you can attach any relevant screenshots, files and links to Timings/spark profiler reports.
      You can also include a link to a heapdump if necessary, but please make sure you don't include any private player data in the heapdump.
      If you suspect this issue is related to a prior issue/PR/commit, please mention it here.

