#!/bin/bash

# ==============================================================================
# Script Name: download_packages.sh
# Description: Reads a text file containing a list of installed packages
#              (generated by dnf list installed) and downloads the RPMs
#              along with their dependencies into a specific directory.
# ==============================================================================

# Check if the user provided an input file
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <path_to_installed_packages_file1.txt> [file2.txt ...]"
    echo "Example: $0 server1_packages.txt server2_packages.txt"
    exit 1
fi

INPUT_FILE="$1"
DEST_DIR="offline_packages_$(date +%Y%m%d_%H%M%S)"

# Function to log messages with a timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

# Verify all input files exist
for file in "$@"; do
    if [ ! -f "$file" ]; then
        log "Error: File '$file' not found."
        exit 1
    fi
done

# Function to create a local repository
create_local_repo() {
    local repo_dir="$1"
    log "Creating local YUM/DNF repository in: $repo_dir"

    # Ensure createrepo is installed
    log "Verifying 'createrepo' is installed..."
    sudo dnf install -y createrepo >/dev/null 2>&1

    if command -v createrepo &> /dev/null; then
        log "Generating repository metadata..."
        createrepo "$repo_dir"
        if [ $? -eq 0 ]; then
            log "Successfully created repository metadata."
        else
            log "Error: Failed to create repository metadata."
        fi
    else
        log "Error: 'createrepo' command not found even after installation attempt."
    fi
}

# Function to create a tar.gz archive of the repository
create_archive() {
    local repo_dir="$1"
    local archive_name="${repo_dir}.tar.gz"
    log "Creating compressed archive: $archive_name"

    # Create the tar.gz file silently (-z for gzip, -c for create, -f for file)
    tar -czf "$archive_name" "$repo_dir"

    if [ $? -eq 0 ]; then
        log "Successfully created archive: $(pwd)/$archive_name"
    else
        log "Error: Failed to create tar archive."
    fi
}

# Function to clean up the source directory after archiving
cleanup_source_dir() {
    local repo_dir="$1"
    local archive_name="${repo_dir}.tar.gz"
    echo ""
    
    # Verify the archive exists before deleting the source files to prevent data loss
    if [ -f "$archive_name" ]; then
        log "Archive verified. Deleting uncompressed source directory: $repo_dir"
        rm -rf "$repo_dir"
        log "Source directory deleted successfully."
    else
        log "Warning: Archive not found. Skipping cleanup to preserve downloaded files."
    fi
}

log "Preparing to download packages to: $(pwd)/$DEST_DIR"
mkdir -p "$DEST_DIR"

# Install dnf-plugins-core to ensure we have the 'dnf download' command
log "Verifying 'dnf-plugins-core' is installed..."
sudo dnf install -y dnf-plugins-core >/dev/null 2>&1

# Extract package names.
# We skip the "Installed Packages" header line, ignore empty lines, and deduplicate.
log "Parsing and deduplicating package lists..."
PACKAGES=$(awk '/^Installed/ {next} NF>0 {print $1}' "$@" | sort -u)

TOTAL_PKGS=$(echo "$PACKAGES" | wc -w)
log "Found $TOTAL_PKGS packages. Starting download with dependency resolution..."
log "This may take a substantial amount of time depending on your network..."

# Download the packages and dependencies.
# We pipe the packages into xargs to prevent "argument list too long" errors.
# --resolve: Resolves and downloads dependencies
# --alldeps: Ensures all dependencies are downloaded, not just missing ones
echo "$PACKAGES" | xargs sudo dnf download --resolve --alldeps --destdir="$DEST_DIR"

# Check exit status
if [ $? -eq 0 ]; then
    log "Success! All available packages and dependencies were downloaded."
else
    log "Warning: The download process finished, but some packages may have failed."
    log "(This often happens with custom/local RPMs that are no longer in your active DNF repositories)."
fi

# Generate the local repository metadata
create_local_repo "$DEST_DIR"

# Create a compressed archive of the repository
create_archive "$DEST_DIR"

# Clean up the uncompressed source files
cleanup_source_dir "$DEST_DIR"

log "Process complete! Final archive location: $(pwd)/${DEST_DIR}.tar.gz"